language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -r requirements.txt; pip install coveralls; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install -r requirements.txt; pip install coveralls; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install -r requirements.txt; pip install coveralls; fi"
  - pip install coveralls
script:
  - "coverage run --source=apps -m py.test"

after_success:
  - COERALLS_REPO_TOKEN=LcHkYOvfnUo5Vicw7j8OroDSYjc9U75iV coveralls
